node:
  type: _
  port: _  # Same as server.connector.port
  bootstrapIP: 127.0.0.1
  bootstrapPort: 9080

assets:
  overrides:
    /: ../angularjs/app

server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  connector:
    type: http
    port: _

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  appenders:
    - type: console
